#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SIM_ROOT="$ROOT/simulate_env"
SIM_HERMES="$SIM_ROOT/.hermes"
REAL_HERMES="${HERMES_HOME:-$HOME/.hermes}"

RESET_SESSIONS=0
RESET_KANBAN=0
RESET_MEMORY=0
COPY_SAFE_BASELINE=0

usage() {
  cat <<'USAGE'
Usage: bash scripts/prepare-sim-env.sh [options]

Create or reset the repository-local simulation Hermes home:
  simulate_env/.hermes/

Options:
  --copy-safe-baseline   Copy safe non-secret baseline files from real ~/.hermes.
                         Currently copies SOUL.md only when present.

  --reset-sessions       Move simulated state.db/session artifacts to backup.
  --reset-kanban         Move simulated kanban.db artifacts to backup.
  --reset-memory         Move simulated memory_store.db artifacts to backup.
  --reset-history        Equivalent to --reset-sessions --reset-kanban.
  --reset-all            Equivalent to --reset-sessions --reset-kanban --reset-memory.

  -h, --help             Show this help.

Safety:
  This script only mutates simulate_env/.hermes/.
  It must never mutate real ~/.hermes/.
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --copy-safe-baseline)
      COPY_SAFE_BASELINE=1
      ;;
    --reset-sessions)
      RESET_SESSIONS=1
      ;;
    --reset-kanban)
      RESET_KANBAN=1
      ;;
    --reset-memory)
      RESET_MEMORY=1
      ;;
    --reset-history)
      RESET_SESSIONS=1
      RESET_KANBAN=1
      ;;
    --reset-all)
      RESET_SESSIONS=1
      RESET_KANBAN=1
      RESET_MEMORY=1
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown option: %s\n\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

if [ "$SIM_HERMES" = "$REAL_HERMES" ]; then
  printf 'Refusing to operate: simulation path equals real Hermes path: %s\n' "$SIM_HERMES" >&2
  exit 1
fi

case "$SIM_HERMES" in
  "$ROOT"/simulate_env/.hermes) ;;
  *)
    printf 'Refusing to operate outside repository simulation path: %s\n' "$SIM_HERMES" >&2
    exit 1
    ;;
esac

mkdir -p "$SIM_HERMES/profiles"
mkdir -p "$SIM_ROOT/backups"

cat > "$SIM_HERMES/README.simulated-hermes-home.md" <<'EOF'
# Simulated Hermes home

This directory is generated by `scripts/prepare-sim-env.sh`.

It is safe for repository-local file operation testing.
It is not a real Hermes Agent runtime home.
Do not commit generated runtime files from this directory.
EOF

backup_dir=""
ensure_backup_dir() {
  if [ -z "$backup_dir" ]; then
    backup_dir="$SIM_ROOT/backups/pre-reset-$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$backup_dir"
  fi
}

move_if_exists() {
  local rel="$1"
  local src="$SIM_HERMES/$rel"
  if [ -e "$src" ]; then
    ensure_backup_dir
    mkdir -p "$backup_dir/$(dirname "$rel")"
    mv "$src" "$backup_dir/$rel"
    printf 'MOVED simulated %s -> %s\n' "$rel" "${backup_dir#$ROOT/}/$rel"
  fi
}

if [ "$RESET_SESSIONS" -eq 1 ]; then
  move_if_exists "state.db"
  move_if_exists "state.db-wal"
  move_if_exists "state.db-shm"
  move_if_exists "sessions"
fi

if [ "$RESET_KANBAN" -eq 1 ]; then
  move_if_exists "kanban.db"
  move_if_exists "kanban.db-wal"
  move_if_exists "kanban.db-shm"
fi

if [ "$RESET_MEMORY" -eq 1 ]; then
  move_if_exists "memory_store.db"
  move_if_exists "memory_store.db-wal"
  move_if_exists "memory_store.db-shm"
fi

if [ "$COPY_SAFE_BASELINE" -eq 1 ]; then
  if [ -f "$REAL_HERMES/SOUL.md" ]; then
    cp "$REAL_HERMES/SOUL.md" "$SIM_HERMES/SOUL.md"
    printf 'COPIED safe baseline SOUL.md from real Hermes home into simulation.\n'
  else
    printf 'SKIP real SOUL.md not found: %s\n' "$REAL_HERMES/SOUL.md"
  fi
else
  if [ ! -f "$SIM_HERMES/SOUL.md" ]; then
    cat > "$SIM_HERMES/SOUL.md" <<'EOF'
# Simulated default SOUL

This is a placeholder for simulation only.
It is not copied from the real Hermes home unless `--copy-safe-baseline` is used.
EOF
    printf 'CREATED placeholder simulated SOUL.md\n'
  fi
fi

printf '\nSimulation Hermes home prepared:\n  %s\n' "$SIM_HERMES"
printf '\nNext command:\n  bash scripts/verify-sim-layout.sh\n'
